disabled_rules:
  - force_cast
  - type_name
  - variable_name
  - function_body_length
  - line_length
  - type_body_length
  - file_length
  - trailing_comma
  - nesting
  - large_tuple
  - cyclomatic_complexity
  - generic_type_name
excluded:
  - Pods
